data_upload:
  date: "2025-06-07"
  chunks_dir: data/chunks
  duckdb_filepath: "data/raw_data.db"
data_analyze:
  report_filepath: "data/report.db"
dashboard_run:
  build: false
  container_name: metaduck
  port: 3000