query:
  create:
    table:
      raw_summoner_game_logs: |
        CREATE TABLE IF NOT EXISTS raw_summoner_game_logs (
            match_id VARCHAR NOT NULL,
            summoner_id VARCHAR NOT NULL,
            tier VARCHAR NOT NULL,
            rank VARCHAR,
            team_id INTEGER NOT NULL,
            end_of_game_result BOOLEAN NOT NULL,
            game_start_timestamp TIMESTAMP NOT NULL,
            game_end_timestamp TIMESTAMP,
            game_duration INTERVAL,
            game_mode VARCHAR NOT NULL,
            queue_id INTEGER NOT NULL,
            queue_description VARCHAR,
            champion_id INTEGER NOT NULL,
            champion_name VARCHAR NOT NULL,
            individual_position VARCHAR NOT NULL,
            team_position VARCHAR NOT NULL,
            summoner_spell1_id INTEGER NOT NULL,
            summoner_spell2_id INTEGER NOT NULL,
            summoner_spell1_casts INTEGER NOT NULL,
            summoner_spell2_casts INTEGER NOT NULL,
            kills INTEGER NOT NULL,
            deaths INTEGER NOT NULL,
            assists INTEGER NOT NULL,
            longest_time_living INTEGER NOT NULL,
            magic_damage_to_champion INTEGER NOT NULL,
            physical_damage_to_champion INTEGER NOT NULL,
            vision_score INTEGER NOT NULL,
            wards_placed INTEGER NOT NULL,
            wards_killed INTEGER NOT NULL,
            baron_kills INTEGER NOT NULL,
            dragon_kills INTEGER NOT NULL,
            voidmonster_kills INTEGER NOT NULL,
            gold_earned INTEGER NOT NULL,
            item0_id INTEGER,
            item1_id INTEGER,
            item2_id INTEGER,
            item3_id INTEGER,
            item4_id INTEGER,
            item5_id INTEGER,
            item6_id INTEGER,
            minion_cs INTEGER NOT NULL,
            jungle_cs INTEGER NOT NULL,
            game_ended_early_surrender BOOLEAN NOT NULL,
            game_ended_surrender BOOLEAN NOT NULL,
            kda FLOAT NOT NULL,
            total_ping_count INTEGER NOT NULL,
            primary_perk_style INTEGER NOT NULL,
            primary_perk1 INTEGER NOT NULL,
            primary_perk2 INTEGER NOT NULL,
            primary_perk3 INTEGER NOT NULL,
            sub_perk_style INTEGER NOT NULL,
            sub_perk1 INTEGER NOT NULL,
            sub_perk2 INTEGER NOT NULL,
            PRIMARY KEY (match_id, summoner_id)  
        );
  insert:
    raw_summoner_game_logs: |
      INSERT OR REPLACE INTO raw_summoner_game_logs
      SELECT
        CAST(match_id AS VARCHAR),
        CAST(summoner_id AS VARCHAR),
        CAST(tier AS VARCHAR),
        CAST(rank AS VARCHAR),
        CAST(team_id AS INTEGER),
        CAST(end_of_game_result AS BOOLEAN),
        CAST(game_start_timestamp AS TIMESTAMP),
        CAST(game_end_timestamp AS TIMESTAMP),
        CAST((game_duration / 1000000000)::VARCHAR || ' seconds' AS INTERVAL),
        CAST(game_mode AS VARCHAR),
        CAST(queue_id AS INTEGER),
        CAST(queue_description AS VARCHAR),
        CAST(champion_id AS INTEGER),
        CAST(champion_name AS VARCHAR),
        CAST(individual_position AS VARCHAR),
        CAST(team_position AS VARCHAR),
        CAST(summoner_spell1_id AS INTEGER),
        CAST(summoner_spell2_id AS INTEGER),
        CAST(summoner_spell1_casts AS INTEGER),
        CAST(summoner_spell2_casts AS INTEGER),
        CAST(kills AS INTEGER),
        CAST(deaths AS INTEGER),
        CAST(assists AS INTEGER),
        CAST(longest_time_living AS INTEGER),
        CAST(magic_damage_to_champion AS INTEGER),
        CAST(physical_damage_to_champion AS INTEGER),
        CAST(vision_score AS INTEGER),
        CAST(wards_placed AS INTEGER),
        CAST(wards_killed AS INTEGER),
        CAST(baron_kills AS INTEGER),
        CAST(dragon_kills AS INTEGER),
        CAST(voidmonster_kills AS INTEGER),
        CAST(gold_earned AS INTEGER),
        CAST(item0_id AS INTEGER),
        CAST(item1_id AS INTEGER),
        CAST(item2_id AS INTEGER),
        CAST(item3_id AS INTEGER),
        CAST(item4_id AS INTEGER),
        CAST(item5_id AS INTEGER),
        CAST(item6_id AS INTEGER),
        CAST(minion_cs AS INTEGER),
        CAST(jungle_cs AS INTEGER),
        CAST(game_ended_early_surrender AS BOOLEAN),
        CAST(game_ended_surrender AS BOOLEAN),
        CAST(kda AS FLOAT),
        CAST(total_ping_count AS INTEGER),
        CAST(primary_perk_style AS INTEGER),
        CAST(primary_perk1 AS INTEGER),
        CAST(primary_perk2 AS INTEGER),
        CAST(primary_perk3 AS INTEGER),
        CAST(sub_perk_style AS INTEGER),
        CAST(sub_perk1 AS INTEGER),
        CAST(sub_perk2 AS INTEGER)
      FROM '{}';
setting:
  save_format: csv # csv, parquet