query:
  create:
    table:
      raw_summoner_game_logs: |
        CREATE TABLE IF NOT EXISTS raw_summoner_game_logs (
            match_id VARCHAR NOT NULL,
            summoner_id VARCHAR NOT NULL,
            tier VARCHAR NOT NULL,
            rank VARCHAR,
            team_id INTEGER NOT NULL,
            end_of_game_result BOOLEAN NOT NULL,
            game_start_timestamp TIMESTAMP NOT NULL,
            game_end_timestamp TIMESTAMP,
            game_duration INTERVAL,
            game_mode VARCHAR NOT NULL,
            queue_id INTEGER NOT NULL,
            queue_description VARCHAR NOT NULL,
            champion_id INTEGER NOT NULL,
            champion_name VARCHAR NOT NULL,
            individual_position VARCHAR NOT NULL,
            team_position VARCHAR NOT NULL,
            summoner_spell1_id INTEGER NOT NULL,
            summoner_spell2_id INTEGER NOT NULL,
            summoner_spell1_casts INTEGER NOT NULL,
            summoner_spell2_casts INTEGER NOT NULL,
            kills INTEGER NOT NULL,
            deaths INTEGER NOT NULL,
            assists INTEGER NOT NULL,
            longest_time_living INTEGER NOT NULL,
            magic_damage_to_champion INTEGER NOT NULL,
            physical_damage_to_champion INTEGER NOT NULL,
            vision_score INTEGER NOT NULL,
            wards_placed INTEGER NOT NULL,
            wards_killed INTEGER NOT NULL,
            baron_kills INTEGER NOT NULL,
            dragon_kills INTEGER NOT NULL,
            voidmonster_kills INTEGER NOT NULL,
            gold_earned INTEGER NOT NULL,
            item0_id INTEGER,
            item1_id INTEGER,
            item2_id INTEGER,
            item3_id INTEGER,
            item4_id INTEGER,
            item5_id INTEGER,
            item6_id INTEGER,
            minion_cs INTEGER NOT NULL,
            jungle_cs INTEGER NOT NULL,
            game_ended_early_surrender BOOLEAN NOT NULL,
            game_ended_surrender BOOLEAN NOT NULL,
            kda FLOAT NOT NULL,
            total_ping_count INTEGER NOT NULL,
            primary_perk_style INTEGER NOT NULL,
            primary_perk1 INTEGER NOT NULL,
            primary_perk2 INTEGER NOT NULL,
            primary_perk3 INTEGER NOT NULL,
            sub_perk_style INTEGER NOT NULL,
            sub_perk1 INTEGER NOT NULL,
            sub_perk2 INTEGER NOT NULL,
            PRIMARY KEY (match_id, summoner_id)  
        );
      sampled_summoners: |
        CREATE TABLE IF NOT EXISTS sampled_summoners (
            summoner_id VARCHAR PRIMARY KEY,
            tier VARCHAR NOT NULL,
            rank VARCHAR
        );

setting:
  save_format: csv # csv, parquet