query:
  db:
    create:
      db:
        metabase: |
          CREATE DATABASE metabase;
      table:
        summoner: |
          CREATE TABLE IF NOT EXISTS summoner (
              summoner_id VARCHAR PRIMARY KEY,
              puuid VARCHAR,
              game_name VARCHAR,
              game_tag VARCHAR
          );
        summoner_league: |
          CREATE TABLE IF NOT EXISTS summoner_league (
              league_id VARCHAR,
              summoner_id VARCHAR PRIMARY KEY,
              tier VARCHAR,
              rank VARCHAR,
              league_points INTEGER,
              veteran BOOLEAN,
              inactive BOOLEAN,
              fresh_blood BOOLEAN,
              hot_streak BOOLEAN,
              
              CONSTRAINT fk_summoner
                  FOREIGN KEY (summoner_id)
                  REFERENCES summoner(summoner_id)
                  ON DELETE CASCADE
          );
        summoner_match: |
          CREATE TABLE IF NOT EXISTS summoner_match (
              match_id VARCHAR,
              summoner_id VARCHAR,
              team_id INTEGER,
              end_of_game_result BOOLEAN,
              game_start_timestamp TIMESTAMP,
              game_end_timestamp TIMESTAMP,
              game_duration INTERVAL,
              champion_id INTEGER,
              champion_name VARCHAR,
              individual_position VARCHAR,
              team_position VARCHAR,
              summoner_spell1_id INTEGER,
              summoner_spell2_id INTEGER,
              summoner_spell1_casts INTEGER,
              summoner_spell2_casts INTEGER,
              kills INTEGER,
              deaths INTEGER,
              assists INTEGER,
              longest_time_living INTEGER,
              magic_damage_to_champion INTEGER,
              physical_damage_to_champion INTEGER,
              vision_score INTEGER,
              wards_placed INTEGER,
              wards_killed INTEGER,
              baron_kills INTEGER,
              dragon_kills INTEGER,
              voidmonster_kills INTEGER,
              gold_earned INTEGER,
              item0_id INTEGER,
              item1_id INTEGER,
              item2_id INTEGER,
              item3_id INTEGER,
              item4_id INTEGER,
              item5_id INTEGER,
              item6_id INTEGER,
              minion_cs INTEGER,
              jungle_cs INTEGER,
              game_ended_early_surrender BOOLEAN,
              game_ended_surrender BOOLEAN,
              kda FLOAT,
              total_ping_count INTEGER,
              primary_perk_style INTEGER,
              primary_perk1 INTEGER,
              primary_perk2 INTEGER,
              primary_perk3 INTEGER,
              sub_perk_style INTEGER,
              sub_perk1 INTEGER,
              sub_perk2 INTEGER,
              PRIMARY KEY (match_id, summoner_id),
              
              CONSTRAINT fk_summoner
                  FOREIGN KEY (summoner_id)
                  REFERENCES summoner(summoner_id)
                  ON DELETE CASCADE
          );
  dwh:
    create:
      db:
        metabase: |
          CREATE DATABASE metabase;
      table:
        summoner: |
          CREATE TABLE IF NOT EXISTS summoner (
              summoner_id VARCHAR PRIMARY KEY,
              puuid VARCHAR,
              game_name VARCHAR,
              game_tag VARCHAR
          );
        summoner_league: |
          CREATE TABLE IF NOT EXISTS summoner_league (
              league_id VARCHAR,
              summoner_id VARCHAR PRIMARY KEY,
              tier VARCHAR,
              rank VARCHAR,
              league_points INTEGER,
              veteran BOOLEAN,
              inactive BOOLEAN,
              fresh_blood BOOLEAN,
              hot_streak BOOLEAN
          );
        summoner_match: |
          CREATE TABLE IF NOT EXISTS summoner_match (
              match_id VARCHAR,
              summoner_id VARCHAR,
              team_id INTEGER,
              end_of_game_result BOOLEAN,
              game_start_timestamp TIMESTAMP,
              game_end_timestamp TIMESTAMP,
              game_duration INTERVAL,
              queue_id INTEGER,
              queue_description VARCHAR,
              champion_id INTEGER,
              champion_name VARCHAR,
              individual_position VARCHAR,
              team_position VARCHAR,
              summoner_spell1_id INTEGER,
              summoner_spell2_id INTEGER,
              summoner_spell1_casts INTEGER,
              summoner_spell2_casts INTEGER,
              kills INTEGER,
              deaths INTEGER,
              assists INTEGER,
              longest_time_living INTEGER,
              magic_damage_to_champion INTEGER,
              physical_damage_to_champion INTEGER,
              vision_score INTEGER,
              wards_placed INTEGER,
              wards_killed INTEGER,
              baron_kills INTEGER,
              dragon_kills INTEGER,
              voidmonster_kills INTEGER,
              gold_earned INTEGER,
              item0_id INTEGER,
              item1_id INTEGER,
              item2_id INTEGER,
              item3_id INTEGER,
              item4_id INTEGER,
              item5_id INTEGER,
              item6_id INTEGER,
              minion_cs INTEGER,
              jungle_cs INTEGER,
              game_ended_early_surrender BOOLEAN,
              game_ended_surrender BOOLEAN,
              kda FLOAT,
              total_ping_count INTEGER,
              primary_perk_style INTEGER,
              primary_perk1 INTEGER,
              primary_perk2 INTEGER,
              primary_perk3 INTEGER,
              sub_perk_style INTEGER,
              sub_perk1 INTEGER,
              sub_perk2 INTEGER,

              PRIMARY KEY (match_id, summoner_id)
          );
setting:
  save_format: csv # csv, parquet