data_collect:
  date: "2025-05-14"
  queue: RANKED_SOLO_5x5
  shards_dir: data/shards
  sample_size: 10000
  resume: true
  recipe:
    - tier: GOLD
      division: I
      ratio: 0.0242
    - tier: GOLD
      division: II
      ratio: 0.0391
    - tier: GOLD
      division: III
      ratio: 0.0482
    - tier: GOLD
      division: IV
      ratio: 0.0774
    - tier: SILVER
      division: I
      ratio: 0.0332
    - tier: SILVER
      division: II
      ratio: 0.0467
    - tier: SILVER
      division: III
      ratio: 0.0512
    - tier: SILVER
      division: IV
      ratio: 0.0652
data_upload:
  duckdb_filepath: "data/raw_data.db"
data_analyze:
  report_filepath: "data/report.db"