data_collect:
  date: "2025-05-14"
  queue: RANKED_SOLO_5x5
  shards_dir: data/shards
  sample_size: 10000
  resume: true
  recipe:
    - tier: PLATINUM
      division: I
      ratio: 0.0167
    - tier: PLATINUM
      division: II
      ratio: 0.0256
    - tier: PLATINUM
      division: III
      ratio: 0.0320
    - tier: PLATINUM
      division: IV
      ratio: 0.0545
data_upload:
  duckdb_filepath: "data/raw_data.db"
data_analyze:
  report_filepath: "data/report.db"